version: '3.8'
services:
  pet-app:
    build:
      context: . 
      target: dev
    deploy: 
      replicas: 5  
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
  
    networks:
      - balancing


  balancer:
    image: nginx:stable-alpine
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - pet-app
    networks:
      - balancing

volumes:
  mysql-vol:
  postgres-vol: 

networks: 
  mysql-net:
  postgres-net: 
  balancing:
    


    
