apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-app
        image: rashadahmed424/spring-pet-app:2.7.8-2
        envFrom:
          - configMapRef:
              name: pet-cm
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
