apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
      - name: mysql-pod
        image: mysql
        envFrom:
          - configMapRef:
              name: mysql-cm

        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: my-vol

      volumes:
        - name: my-vol
          persistentVolumeClaim:
            claimName: pet-pvc

