version: '3.8'
services:
  pet-app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://pet-db:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    ports:
      - "9000:8080" 
    networks:
      - pet-network
    depends_on:
      pet-db:
          condition: service_healthy


  pet-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    volumes:
      - pet-data:/var/lib/pet-app-data
    networks:
      - pet-network
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  pet-data:
  
networks:
  pet-network:
    driver: bridge
    


    


    
